### ISSUE TITLE
any idea about compile on windows?

### ISSUE THREAD

**Issue by DK1998U** [rtravis/SkypeCacheViewer#2]
i had levelcb.lib  when i try to compile this project on windows with vs2019, i got the following errors:

base/logging.h  no base::char16

**Comment by rtravis** [comment]
Currently compilation on Windows is not supported. Many files from the Chromium project needed for the Windows compilation have not been included. However, if you want to run on Windows you may try to compile under Cygwin or use the Windows Subsystem for Linux (WSL).

**Comment by rtravis** [comment]
We're not going to support Windows for now, see previous comment.
